package com.josan.vistas;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class VentanaTabla {
    private JPanel panel1;
    public JTable tablaMultiusos;
    private JScrollPane scroll;
    public DefaultTableModel tablaMultiusosModelo;
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        scroll = new JScrollPane();
        CellConstraints cc = new CellConstraints();
        panel1.add(scroll, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        tablaMultiusos = new JTable();
        scroll.setViewportView(tablaMultiusos);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public void VentanaPrincipal() {

    }

    public void initializeWindow() {
        JFrame frame = new JFrame("Ventana Principal");
        frame.setContentPane(panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.tablaMultiusosModelo = new DefaultTableModel();
        this.tablaMultiusos.setModel(this.tablaMultiusosModelo);
        frame.setVisible(true);
    }
}
